{% set name = "types-python-slugify" %}
{% set version = "8.0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-python-slugify-{{ version }}.tar.gz
  sha256: de237b01c69ad3a57ae36a0e8a6a0c65b47bac529483007c1cae2d424cb07cc8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/slugify-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-slugify
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
